### ISSUE TITLE
Сравнение вещественных чисел?

### ISSUE THREAD

**Issue by spogozhev** [rism1/Pratice2021#13]
https://github.com/rism1/Pratice2021/blob/a1b0ba3481a9906645264f1e459b783a4ce08281/Homework/hw4%20(11.10.2021)/Value%20Of%20Pi.cpp#L44

Не следует таким образом сравнивать вещественные числа. Необходимо анализировать как меняется сумма. Как только изменение суммы не будет превосходить заданной точности вычислений, то следует остановить вычисления.

**Comment by rism1** [comment]
Сделал небольшой рефакторинг, недочет понял, только принцип точности в программе немного отличается, поэтому вычисления чуть другие.
