### ISSUE TITLE
Ошибка в вычислении обратной матрицы

### ISSUE THREAD

**Issue by spogozhev** [rism1/Pratice2021#17]
https://github.com/rism1/Pratice2021/blob/8de8b0be3e1d58f5325c13256e9ef03b5451b21a/Homework/hw%20(15.11.2021)/det%20and%20inv.cpp#L141

Для матрицы [0 0 1; 0 1 0; 1 0 0] выдает в качестве обратной матрицы единичную.

**Comment by rism1** [comment]
Исправил, проблема была в функции det(), менявшая входную матрицу, которая далее использовалась в программе.
