### ISSUE TITLE
Для больших целых может не работать

### ISSUE THREAD

**Issue by spogozhev** [rism1/Pratice2021#20]
https://github.com/rism1/Pratice2021/blob/5517a11a14f39e61497c7ec8b2b03c1f21c3fbf5/Homework/hw%20(25.10.2021)/Inverted%20Tower.cpp#L27

Не следует переводить в double, так как для больших значений N не получатся точные вычисления. 
Реализуйте алгоритм без необходимости вычисления корня.

**Comment by rism1** [comment]
Исправил. В старом решении в принципе подразумевалась немного другая башня (я невнимательно прочитал условие).
